services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports:
      - "1974:1972"
      - "42773:52773"
      - "43772:53773"
    volumes:
      - ./:/irisrun/repo
